-- hive中把一行转成多行
SELECT
    TRACKING_NO,
    PUR_ORDER_SN2
FROM
(SELECT
    TRACKING_NO,
    PUR_ORDER_SN
FROM  WHO_WMS_PUR_DELIVER_RECEIPT
WHERE TRACKING_NO = '510019436417') A
LATERAL VIEW EXPLODE(SPLIT(PUR_ORDER_SN, '，')) MYTABLE AS PUR_ORDER_SN2;
